# Generated by Django 5.2.7 on 2025-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='end_time',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
