# Generated by Django 5.2.7 on 2025-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_start_time_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
