# Generated by Django 5.2.7 on 2025-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_context_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='memory_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
