# Generated by Django 5.2.7 on 2025-11-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conversation_memory_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
