# Generated by Django 5.2.8 on 2025-11-19 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_calendarevent_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('trace', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_runs', to='core.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
