# Generated by Django 5.2.8 on 2025-12-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_groups_alter_user_user_permissions_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_scores', to='core.candidate')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='core.jobrole')),
            ],
            options={
                'unique_together': {('candidate', 'job_role')},
            },
        ),
    ]
