# Generated by Django 5.2.8 on 2026-01-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_google_access_token_user_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_token_expires',
        ),
    ]
