# Generated by Django 5.2.8 on 2026-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
