# Generated by Django 5.2.8 on 2026-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_connected_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
