# Generated by Django 5.2.8 on 2026-02-26 13:16

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization_google_connected_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='HRMSSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrms_type', models.CharField(default='harvey', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(help_text='Base URL for the HRMS API')),
                ('auth_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Encrypted API Access Token')),
                ('departments_endpoint', models.CharField(default='/api/v1/departments', max_length=255)),
                ('employees_endpoint', models.CharField(default='/api/v1/employees', max_length=255)),
                ('jobs_endpoint', models.CharField(default='/api/v1/jobs', max_length=255)),
                ('candidates_endpoint', models.CharField(default='/api/v1/candidates', max_length=255)),
                ('interviews_endpoint', models.CharField(default='/api/v1/interviews', max_length=255)),
                ('onboarding_endpoint', models.CharField(default='/api/v1/onboarding', max_length=255)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_system_config', to='core.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='HRMSIntegrationConfig',
        ),
    ]
