# Generated by Django 5.2.8 on 2026-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_leaverequest_status_hrmssystemconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmssystemconfig',
            name='edit_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hrmssystemconfig',
            name='edit_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
