# Generated by Django 5.2.8 on 2026-02-26 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hrmssystemconfig_edit_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMSEndpointMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.CharField(help_text='Relative path of the external API, e.g. /api/v2/leaves', max_length=255)),
                ('target_model', models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate'), ('Interview', 'Interview'), ('LeaveRequest', 'Leave Request'), ('JobRole', 'Job Role')], help_text='Harvey model to sync the data into', max_length=50)),
                ('sample_json', models.TextField(blank=True, help_text='Raw JSON sample response used for compatibility validation', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hrms_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_mappings', to='core.hrmssystemconfig')),
            ],
            options={
                'unique_together': {('hrms_config', 'endpoint_url')},
            },
        ),
    ]
