# Generated by Django 5.2.8 on 2026-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hrmsendpointmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('logger_name', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=200)),
                ('func_name', models.CharField(blank=True, max_length=200)),
                ('line_no', models.PositiveIntegerField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('exc_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'App Log',
                'verbose_name_plural': 'App Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
