# Generated by Django 5.2.8 on 2026-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_organization_google_connected_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_connected_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
