# Generated by Django 6.0.2 on 2026-03-22 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_google_connected_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('leave_type', models.CharField(max_length=50)),
                ('total_allocated', models.FloatField(default=0.0)),
                ('used', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'unique_together': {('employee', 'year', 'leave_type')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('leave_type', models.CharField(max_length=50)),
                ('default_allocated', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'year', 'leave_type')},
            },
        ),
    ]
