# Generated by Django 6.0.2 on 2026-03-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_leaverequest_is_deducted_leavebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_token', models.CharField(blank=True, max_length=64, null=True)),
                ('edit_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_system_config', to='core.organization')),
            ],
        ),
    ]
