# Generated by Django 6.0.2 on 2026-04-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_leavesystemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(default='scheduled', max_length=50),
        ),
    ]
