# Generated by Django 6.0.2 on 2026-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_interview_description_interview_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_feedback', 'Pending Feedback')], default='scheduled', max_length=50),
        ),
    ]
