# Generated by Django 6.0.2 on 2026-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('online', 'Online (Google Meet)'), ('in_person', 'In-Person')], default='online', max_length=20),
        ),
    ]
