# Generated by Django 6.0.2 on 2026-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_interview_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assessment'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
