# Generated by Django 6.0.2 on 2026-06-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
